tests-api: add _hooks variable for dtf_fail
* share/dtf/lib/tests (dtf_fail): Add new $dtf_fail_hooks
variable.  It is aimed to contain list of shell functions to be
execute upon failure.

diff --git a/share/dtf/lib/tests b/share/dtf/lib/tests
--- a/share/dtf/lib/tests
+++ b/share/dtf/lib/tests
@@ -14,6 +14,14 @@ dtf_skip ()
 dtf_fail ()
 {
     test -n "$1" && echo >&2 "$1"
+    test -z "$dtf_fail_hooks" && exit 1
+
+    echo >& "running dtf_fail hooks $dtf_fail_hooks"
+    for _i_hook in $dtf_fail_hooks
+    do
+      $_i_hook
+    done
+
     exit 1
 }
 
